// <auto-generated />
namespace App_test.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mg01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mg01));
        
        string IMigrationMetadata.Id
        {
            get { return "202106121506039_mg01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
